
package com.mulesoft.example.estore.clients.provider.vangoghpaintstore;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sat Jun 02 00:51:48 GMT-03:00 2012
 * Generated source version: 2.1.3
 * 
 */

public final class B2BStore_B2BStorePort_Client {

    private static final QName SERVICE_NAME = new QName("http://vangoghpaintstore.provider.services.estore.example.mulesoft.com/", "B2BStoreService");

    private B2BStore_B2BStorePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = B2BStoreService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        B2BStoreService ss = new B2BStoreService(wsdlURL, SERVICE_NAME);
        B2BStore port = ss.getB2BStorePort();  
        
        {
        System.out.println("Invoking placeOrder...");
        com.mulesoft.example.estore.clients.provider.vangoghpaintstore.DeliveryOrder _placeOrder_arg0 = null;
        java.lang.String _placeOrder__return = port.placeOrder(_placeOrder_arg0);
        System.out.println("placeOrder.result=" + _placeOrder__return);


        }
        {
        System.out.println("Invoking getProductInfo...");
        java.lang.String _getProductInfo_arg0 = "";
        com.mulesoft.example.estore.clients.provider.vangoghpaintstore.Product _getProductInfo__return = port.getProductInfo(_getProductInfo_arg0);
        System.out.println("getProductInfo.result=" + _getProductInfo__return);


        }
        {
        System.out.println("Invoking listProducts...");
        java.util.List<com.mulesoft.example.estore.clients.provider.vangoghpaintstore.Product> _listProducts__return = port.listProducts();
        System.out.println("listProducts.result=" + _listProducts__return);


        }

        System.exit(0);
    }

}
