package com.mulesoft.example.estore.clients.provider.vangoghpaintstore;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon May 28 13:20:45 GMT-03:00 2012
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://vangoghpaintstore.provider.services.estore.example.mulesoft.com/", name = "B2BStore")
@XmlSeeAlso({ObjectFactory.class})
public interface B2BStore {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listProducts", targetNamespace = "http://vangoghpaintstore.provider.services.estore.example.mulesoft.com/", className = "com.mulesoft.example.estore.clients.provider.vangoghpaintstore.ListProducts")
    @ResponseWrapper(localName = "listProductsResponse", targetNamespace = "http://vangoghpaintstore.provider.services.estore.example.mulesoft.com/", className = "com.mulesoft.example.estore.clients.provider.vangoghpaintstore.ListProductsResponse")
    @WebMethod
    public java.util.List<com.mulesoft.example.estore.clients.provider.vangoghpaintstore.Product> listProducts();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "orderProduct", targetNamespace = "http://vangoghpaintstore.provider.services.estore.example.mulesoft.com/", className = "com.mulesoft.example.estore.clients.provider.vangoghpaintstore.OrderProduct")
    @ResponseWrapper(localName = "orderProductResponse", targetNamespace = "http://vangoghpaintstore.provider.services.estore.example.mulesoft.com/", className = "com.mulesoft.example.estore.clients.provider.vangoghpaintstore.OrderProductResponse")
    @WebMethod
    public java.lang.String orderProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
